spring:
  data:
    mongodb:
      database: library
      auto-index-creation: true
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      port: 27017
      host: localhost
      authentication-database: admin