spring:
  profiles:
    default: dev
server:
  error:
    include-message: always

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG